#!/bin/sh
#
#board management
#

#device_info $DEVICE_MODEL $HV
DEVICE_MODEL="`/usr/bin/pro_ctl_util -i | awk -F ":" '/product type/{print $2}'`"
echo "$DEVICE_MODEL"
device_info $DEVICE_MODEL

#
# drivers
#
cd /lib/modules/2.6.15/net/
insmod ag7240_mod.ko
insmod ath_hal.ko
insmod wlan.ko
insmod ath_rate_atheros.ko
insmod ath_dev.ko
insmod ath_pci.ko
insmod ath_pktlog.ko
insmod wlan_acl.ko
insmod wlan_ccmp.ko
insmod wlan_scan_ap.ko
insmod wlan_scan_sta.ko
insmod wlan_tkip.ko
insmod wlan_wep.ko
insmod wlan_xauth.ko
insmod capwap_split_fast.ko
#iwpriv wifi0 setCountryID 0x1ff

# loopback
#
ifconfig lo 127.0.0.1

#set mac
mac_base="`/usr/sbin/showsysinfo | awk -F ":" '/MAC/{print $2$3$4$5$6$7}'`"
product_type="`/usr/bin/pro_ctl_util -i | awk -F ":" '/product type is/{print $2}' | cut -b 1-3`"
if [ "$product_type" == "AGU" ];then
	#set wifi mac
	mac_org_formed=`set_mac org ${mac_base} `
	ifconfig wifi0 down
	ifconfig wifi0 hw ether ${mac_org_formed}
	#set eth mac
	mac_org_formed=`set_mac upper ${mac_base} `
	ifconfig eth1 down
	ifconfig eth1 hw ether $mac_org_formed
else
	#set eth mac
	mac_org_formed=`set_mac org ${mac_base} `
	ifconfig eth1 down
	ifconfig eth1 hw ether $mac_org_formed
	#set wifi mac
	mac_org_formed=`set_mac upper ${mac_base} `
	ifconfig wifi0 down
	ifconfig wifi0 hw ether ${mac_org_formed}
fi

brctl addbr default
brctl setfd default 1
#brctl addif default eth0
brctl addif default eth1
ifconfig eth0 up
ifconfig eth1 up
ifconfig default 0.0.0.0 up

#init app
showsysinfo | grep Software > /tmp/issue
showsysinfo | grep MAC >> /tmp/issue
showsysinfo | grep SN >> /tmp/issue
/usr/sbin/telnetd -f /tmp/issue
if [ ! -f /jffs/apinfo.conf ];then
	cp -f /etc/wlan/apinfo.conf /jffs
fi
