//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 5:26:00 PM on Friday, April 02, 2004
//
//	Generated for file: H:\gsoap2.6\win\stockquote\Rsc\StockQuote.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"StockQuote"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainRunButton                             1001	//(Left Origin = 9, Top Origin = 73, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainSymbolField                           1002	//(Left Origin = 65, Top Origin = 22, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainResultField                           1005	//(Left Origin = 64, Top Origin = 48, Width = 50, Height = 12, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1003Label                      1003	//(Left Origin = 10, Top Origin = 21, Usable = 1, Font = Standard)
#define MainUnnamed1004Label                      1004	//(Left Origin = 12, Top Origin = 48, Usable = 1, Font = Standard)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 22, Top Origin = 22, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define Soap_errorAlert                           1100
#define Soap_errorOK                              0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStockQuote                1000


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

