LDFLAGS:=-shared -fPIC

all:
	rm -f *.a *.o *.so
	$(CC) -fPIC -c  conf_file_opt.c $(CPPFLAGS) $(EXTRA_CPPFLAGS)
	$(CC) -fPIC -c  ap_interface.c -I../include $(CPPFLAGS) $(EXTRA_CPPFLAGS) 
	${CC} $(LDFLAGS) -Wall -o libapfunc.so ./*.o $(EXTRA_LDFLAGS)

clean:
	rm -f *.a *.o *.so
