cmd_/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.o := mips-linux-uclibc-gcc -Wp,-MD,/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/.athrs_flowmac.o.d  -nostdinc -isystem /home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/gcc-4.3.3/build_mips/staging_dir/usr/bin-ccache/../lib/gcc/mips-linux-uclibc/4.3.3/include -Iinclude  -I/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/linux/kernels/mips-linux-2.6.31/arch/mips/include -include include/linux/autoconf.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -mno-check-zero-division -mabi=32 -G 0 -mno-abicalls -fno-pic -pipe -msoft-float -ffreestanding -march=74kc -Wa,-march=74kc -Wa,--trap -I/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/linux/kernels/mips-linux-2.6.31/arch/mips/include/asm/mach-atheros -I/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/linux/kernels/mips-linux-2.6.31/arch/mips/include/asm/mach-generic -D"VMLINUX_LOAD_ADDRESS=0xffffffff80002000" -fno-stack-protector -fomit-frame-pointer -funit-at-a-time -pipe -mtune=74kc -Os -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -I /home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/include -I /home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/include/phys -I/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/kernels/mips-linux-2.6.31/arch/mips/include -DNO_PUSH_BUTTON=1 -DPC018=1  -DMODULE -mlong-calls -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(athrs_flowmac)"  -D"KBUILD_MODNAME=KBUILD_STR(athrs_gmac)"  -c -o /home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.o /home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.c

deps_/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.o := \
  /home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.c \
    $(wildcard include/config/flowmac.h) \

/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.o: $(deps_/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.o)

$(deps_/home/zhangsiyu/pc018work-v15-at/apv5sdk-v15/build/../linux/drivers/ethernet/athrs_flowmac.o):
