.TH hpavd 7 "Intellon Corporation, Ocala FL USA" "int6000-utils-linux" "Intellon Linux Toolkit"
.SH NAME
hpav - HomePlug AV Packet Daemon
.SH SYNOPSIS
.BR hpavd 
.RI [ options ] 
.SH DESCRIPTION
Displays HomePlug AV ethernet frames transmitted by a HomePlug AV device to the host. It does not display HomePlug AV frames from the host to the device or HomePlug AV frames transmitted over powerline unless they have been forwarded to the host via the local device.
.PP
The program is an example of a simple packet listener and daemon. Consequently, it lacks features. Engineers and software developers can use it to build custom applications. The framework is present but details must be modified or added.
.SH CAVEATS
This program places the selected interface in the promiscuous mode when started and restores the original mode on normal exit. It can fail to restore the orignal mode on abnormal exit. Placing an Ethernet adapter in promiscuous mode cause unwanted interactions with other programs using the same adapter. Select your configuration accordingly.
.SH OPTIONS
.TP
.RB - d
Spawns the program as a background process, or daemon, and returns control of the console to the user. The the foreground process returns immediately but the background process runs until terminated. 
.TP
-\fBi \fIinterface\fR
Names the host ethernet interface to watch. The named interface, such as eth0, eth1 and so on, must be connected to a HomePlug AV ethernet-to-powerline bridge adapter to receive any HomePlug AV traffic. The default interface is \fBeth1\fR.
.TP
.RB - q
Quiet mode. Suppress the printing of the normal message descriptions on \fBstdout\fR.
.TP
.RB - v
Verbose mode. Displays incoming frames in hexadecimal dump format on \fBstdout\fR. This option is independent of option \fB-a\fR which prints VS_ARPC message text on stderr.
.TP
-\fB?\fR, --\fBhelp\fR
Print program help summary on stdout. This option takes precedence over other options on the command line. 
.TP
-\fB!\fR, --\fBversion\fR
Print program version information on stdout. This option takes precedence over other options on the command line. Usethis option when sending screen dumps to Intellon Technical Support so that they know exactly which version of the Linux Toolkit you are using.
See the HomePlug AV Specification for a description of all HomePlug AV message types. See the Intellon INT6000 Firmware Reference Manual for a description of Intellon Vendor Specific message types.
.SH EXAMPLES
The following command monitors the default host interface for HomePlug AV traffic and display incoming frames on the console as they arrive. It will continue to run until the user types ^C or ^Z at the console. Generally, \fBhpavd\fR is run in a separate console window.
.PP
   # hpavd
.PP
The following command monitors host interface \fBeth4\fR for Homeplug AV frames and write them to file \fBhpavd.log\fR. Frames are printed in hexadecimal dump format because option \fB-v\fR is present.
.PP
   # hpavd -v -i eth4 > hpavd.log
.SH DISCLAIMER
Intellon HomePlug AV Vendor Specific Management Message structure and content is proprietary to Intellon Corporation, Ocala FL USA. Consequently, public information is not available. Intellon Corporation reserves the right to modify management message structure and content in future firmware releases without any obligation to notify or compensate users of this program.
.SH SEE ALSO
.BR efsu ( 7 ),
.BR ilt ( 7 )
.SH CREDITS
 Charles Maier <charles.maier@intellon.com>
