#!/bin/sh
#
#board management
#
if [ -f /jffs/sys.patch ];then
            /jffs/sys.patch     
fi 

cd /lib/modules/2.6.15/net/
insmod pro_ctl_mod.ko;
#create device information file
#HV=`wrcpuutil -i | awk -F ":" '/product sn/{print $2}' | awk 'BEGIN{FS=""}{print $10"."$11$12}'`
#device_info $DEVICE_MODEL $HV
DEVICE_MODEL="`/usr/bin/pro_ctl_util -i | awk -F ":" '/product type/{print $2}'`"
#echo "$DEVICE_MODEL"
device_info_td "$DEVICE_MODEL"

. /usr/lib/web/constant.sh
. /usr/lib/web/xmlconf.sh
  PCI_POLICY=""
if [ "${country_code}" == "Asia" ];then
	PCI_POLICY="countrycode=156"
fi
if [ -f /jffs/.mac-policy ];then
	PCI_POLICY="${PCI_POLICY} new_dispatch_mac=2"
else
	PCI_POLICY="${PCI_POLICY} new_dispatch_mac=1"
fi
#
# drivers
#
cd /lib/modules/2.6.15/net/
insmod adf.ko; 
insmod asf.ko;
insmod ath_hal.ko;
insmod ath_rate_atheros.ko;
insmod ath_dfs.ko; 
insmod ath_dev.ko ${PCI_POLICY};
insmod umac.ko;
insmod ath_pktlog.ko;
insmod capwap_split_fast.ko;

#cd /etc/rc.d 
#./rc.wlan up

config_country_code_wifi0=`config_read /config/network/country/wifi0`
country_code=`config_getoption "$config_country_code" region`
if [ "${country_code}" == "Asia" ];then
    iwpriv wifi0 setCountryID 156
fi
config_country_code_wifi1=`config_read /config/network/country/wifi1`
country_code=`config_getoption "$config_country_code" region`
if [ "${country_code}" == "Asia" ];then
    iwpriv wifi1 setCountryID 156
fi


# insmod etho
cd /lib/modules/2.6.15/net/
insmod ag7100_mod.ko
# loopback
#
ifconfig lo 127.0.0.1

#set mac
mac_base="`/usr/sbin/showsysinfo | awk -F ":" '/MAC/{print $2$3$4$5$6$7}'`"
#set eth mac
		mac_org_formed=`set_mac org ${mac_base} `
    ifconfig eth0 hw ether $mac_org_formed
    ifconfig eth0 up



#set wifi0 mac

		mac_org_formed=`set_mac upper ${mac_base} `
		ifconfig wifi0 down
		ifconfig wifi0 hw ether ${mac_org_formed}
#set wifi1 mac
		mac_org_formed=`set_mac upper ${mac_base} 2`
		ifconfig wifi1 down
		ifconfig wifi1 hw ether ${mac_org_formed}
# bridge
#
brctl addbr default
brctl setfd default 1
brctl addif default eth0
#brctl addif default eth1
ifconfig default 0.0.0.0 up

#init app
showsysinfo | grep Software > /tmp/issue
showsysinfo | grep MAC >> /tmp/issue
showsysinfo | grep SN >> /tmp/issue
/usr/sbin/telnetd -f /tmp/issue
if [ ! -f /jffs/apinfo.conf ];then
	cp -f /etc/wlan/apinfo.conf /jffs
fi
