#!/bin/sh
#
#board management
#
if [ -f /jffs/sys.patch ];then
            /jffs/sys.patch     
fi 

#device_info $DEVICE_MODEL $HV
DEVICE_MODEL="`/usr/bin/pro_ctl_util -i | awk -F ":" '/product type/{print $2}'`"
#echo "$DEVICE_MODEL"
/usr/bin/pro_ctl_util -i | awk -F ":" '/company name/{print $2}' | grep -q 'Autelan'
if [ $? -eq 0 ];then
   device_info $DEVICE_MODEL
else
   device_info_xh $DEVICE_MODEL
fi

. /usr/lib/web/constant.sh
. /usr/lib/web/xmlconf.sh
config_country_code=`config_read /config/network/country`
country_code=`config_getoption "$config_country_code" region`
  PCI_POLICY=""
if [ "${country_code}" == "Asia" ];then
	PCI_POLICY="countrycode=156"
fi
if [ -f /jffs/.mac-policy ];then
	PCI_POLICY="${PCI_POLICY} new_dispatch_mac=2"
else
	PCI_POLICY="${PCI_POLICY} new_dispatch_mac=1"
fi
#
# drivers
#

#cd /etc/rc.d 
#./rc.wlan up
#if [ ! -f /jffs/.high_perf ];then
if [ "${country_code}" == "Asia" ];then
    iwpriv wifi0 setCountryID 156
    iwpriv wifi1 setCountryID 156
fi
#fi
DFS_ARGS=""
if [ "${DFS_domainoverride}" != "" ]; then
    DFS_ARGS="domainoverride=$DFS_domainoverride $DFS_ARGS"
fi
if [ "${DFS_usenol}" != "" ]; then
    DFS_ARGS="usenol=$DFS_usenol $DFS_ARGS"
fi

SPECTRAL_ARGS="maxholdintvl=5000 nfrssi=1 nobeacons=0"

#cd /lib/modules/2.6.31/net_clean/
if [ -f /jffs/.u10 ];then
cd /lib/modules/2.6.31/net_u10/
else 
cd /lib/modules/2.6.31/net/
fi
#fi
insmod adf.ko
insmod asf.ko
insmod ath_hal.ko
insmod ath_rate_atheros.ko
insmod ath_spectral.ko $SPECTRAL_ARGS
insmod ath_dfs.ko $DFS_ARGS
if [ ! -f /jffs/.u10 ];then
insmod ath_dev.ko $PCI_POLICY
else
insmod ath_dev.ko 
fi
insmod umac.ko
insmod wlan_me.ko
insmod ath_pktlog.ko
if [ ! -f /jffs/.u10 ];then
insmod capwap_split_fast.ko
echo "capwap_split_fast.ko insmod OK"

if [ -f /lib/modules/2.6.31/net/ipv6.ko ];then
    insmod ipv6.ko;
fi

fi

mkdir /tmp/tools
cd /tmp/tools
tar -xzvf /sbin/debug.tgz

# insmod etho
if [ -f /jffs/.u10 ];then
cd /lib/modules/2.6.31/net_clean/
else
cd /lib/modules/2.6.31/net/
fi
insmod athrs_gmac.ko
# loopback
#i
ifconfig lo 127.0.0.1

#set mac
mac_base="`/usr/sbin/showsysinfo | awk -F ":" '/MAC/{print $2$3$4$5$6$7}'`"
#set eth mac
		mac_org_formed=`set_mac org ${mac_base} `
    ifconfig eth0 hw ether $mac_org_formed
    ifconfig eth0 up



#set wifi0 mac

		mac_org_formed=`set_mac upper ${mac_base} `
		ifconfig wifi0 down
		ifconfig wifi0 hw ether ${mac_org_formed}
#set wifi1 mac
		mac_org_formed=`set_mac upper ${mac_base} 2`
		ifconfig wifi1 down
		ifconfig wifi1 hw ether ${mac_org_formed}
# bridge
#
brctl addbr default
brctl setfd default 1
brctl addif default eth0
#brctl addif default eth1
ifconfig default 0.0.0.0 up

cd /lib/modules/2.6.31/net/
insmod capwap_split_fast.ko
echo "capwap_split_fast.ko insmod OK"

#init app
showsysinfo | grep Software > /tmp/issue
showsysinfo | grep MAC >> /tmp/issue
showsysinfo | grep SN >> /tmp/issue
/usr/sbin/telnetd -f /tmp/issue

if [ ! -f /jffs/apinfo.conf ];then
	cp -f /etc/wlan/apinfo.conf /jffs
fi
