#!/bin/sh
judge=1
count=0

#echo for the device first up or restart
echo \###########################################>> /jffs/burn_in_log

#loop check
while [ $judge -eq 1 ]; do

#count add
let count+=1

#calculate the currently time
hour=`date +"%H"`
minutes=`date +"%M"`
seconds=`date +"%S"`
temperature=`pro_ctl_util -T | awk -F '=' '{print $2}'`

#write the information into the file
echo "count:$count   uptime:$hour:$minutes:$seconds    temperature:$temperature" >> /jffs/burn_in_log
sleep 3600
done
