#!/bin/sh
cd /jffs
rm test -f
touch test
[ -e test ]
if [ $? -eq 0 ];then
	rm test -f 
	[ ! -e test ]
	if [ $? -eq 0 ];then
		echo "flash OK!"
	else 
		echo "flash error"
	fi
else
	echo "flash error"
fi


