/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: wapiPwlanAp.h
* description:  implementation for the header file of wapiPwlanAp.c.
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf,v 1.3.4.2 2006/01/05 16:31:38 dts12 Exp $
 */

#ifndef WAPIPWLANAP_H
#define WAPIPWLANAP_H

#include "cpumemusage.c"  

#define AC_SNMP_CONF  "/etc/snmp/ac_snmp.conf"


#define IFNAME_LEN  20

/* function declarations */
    void init_wapiPwlanAp(void);
    FindVarMethod var_wapiPwlanAp; 
    FindVarMethod var_wapi80211bapUserAssoTable;
    FindVarMethod var_wapiApEthInterfacesTable;
    FindVarMethod var_wapi80211gapUserAssoTable;
    FindVarMethod var_wapiStatsTable;
    FindVarMethod var_wapiSTAPortStatusTable;
    FindVarMethod var_wapiApWifiInterfaceStatisticsTable;
    FindVarMethod var_wapiWlanUserTable;
    FindVarMethod var_wapiApWirelessTable;
    FindVarMethod var_wapiApwapiConfigTable;
    FindVarMethod var_wapiAPESSIDTable;
    FindVarMethod var_wapiMssidTable;
	FindVarMethod var_wapiPowerMgmtTable ;
	FindVarMethod var_wapiAccessControlSettingTable ;
	
   //add by piyongping 2008-11-22
	WriteMethod write_rfPowerManager;
	WriteMethod write_wapiConfigFilterPkts;
    WriteMethod write_wapiStartConfigAP;
    WriteMethod write_wapiConfigFile;
	
    WriteMethod write_wapiApFrequencySwitch;
    WriteMethod write_wapiApWZC;
    WriteMethod write_wapiApARF;
    WriteMethod write_wapiApBRF;
	
    WriteMethod write_apdot11DesiredSSID ;               
    WriteMethod write_wapiapMaxSimultUsers;											
    WriteMethod write_apMaxSimultTraffic;										
    WriteMethod write_apBSSIDEncryption	;

    WriteMethod write_ChStatsChannel;
    WriteMethod write_ChStatsMonitoredTime;
    WriteMethod write_apSnrBSSIDSampleTime;
    WriteMethod write_wapiApUserThresholdCfg;
    WriteMethod write_wapidot11QosEnabled;
    WriteMethod write_WapiAsIP;
    WriteMethod write_WapiAsCert;
    WriteMethod write_WapiUserCert;
    WriteMethod write_WapiInstallCert;

    WriteMethod write_wapiServerURL;
    WriteMethod write_wapiStartUpgrade;

    WriteMethod write_wapiConfigUsersQos;
    WriteMethod write_wapiConfigBandwidthQos;
    WriteMethod write_wapiConfigMultiModeAccessState;
    WriteMethod write_wapiConfigWapiState;
    WriteMethod write_wapiConfigMaxBandwidth;
    WriteMethod write_wapiConfigMaxUsres;
    WriteMethod write_wapiBSSIDMaxUser;
    WriteMethod write_wapiESSIDMaxUser;

    WriteMethod write_wapiapConfigBSSID;
    WriteMethod write_wapidot11DesiredSSID;
    WriteMethod write_wapiBSSIDNumInESSID;
    WriteMethod write_wapiapConfigBSSIDNum;
    WriteMethod write_wapiEAPAuthenSupport;
    WriteMethod write_wapiApWorkMode;
    WriteMethod write_wapiapTxRates;
    WriteMethod write_wapiapBSSIDEncryption;
    WriteMethod write_wapiapDot11aAntennaGain;
    WriteMethod write_wapiapDot11gAntennaGain;
    WriteMethod write_wapiconRadiusServerPort;
    WriteMethod write_wapiconPortalURL;
    WriteMethod write_wapiconDNSServer;
    WriteMethod write_wapidot11QosTrafficClass;

    WriteMethod write_wapiConfigUnicastCipher;
    WriteMethod write_wapiConfigUnicastCipherEnabled;
    WriteMethod write_wapiConfigUnicastCipherSize;
    WriteMethod write_wapiConfigAuthenticationSuite;
    WriteMethod write_wapiConfigAuthenticationSuiteEnabled;
    WriteMethod write_wapidot11AuthenticationAlgorithm;
  
    WriteMethod write_wapiVlanOnOff ;
    WriteMethod write_wapiMssidAdd ;
    WriteMethod write_wapiMssidDel ;
    WriteMethod write_wapiMssidWlanSSID;
    WriteMethod write_wapiMssidHideSSID;
    WriteMethod write_wapiMssidWAPI;
    WriteMethod write_wapiMssidPskType;
    WriteMethod write_wapiMssidPsk;
    WriteMethod write_wapiMssidVlanID;
    WriteMethod write_wapiMssidQos;
    WriteMethod write_wapiMssidMacPolicy;
    WriteMethod write_wapiMssidMaxUser;

    WriteMethod write_wapiApSoftVersion;
    WriteMethod write_wapiConfigfactoryDefault;
    		
    WriteMethod write_wapiRwcommunity;
    WriteMethod write_wapiConfigUserSeparate;
    WriteMethod write_wapiTrapIP;
	//add by piyp 2008-11-21
	WriteMethod write_wapiTrapSecondaryIP;
	WriteMethod write_wapiAccessControlUsers;
	WriteMethod write_wapiAccessControlIpList;
	WriteMethod write_wapiAccessControlEnabled;
	
    WriteMethod write_wapiRocommunity;
    WriteMethod write_wapiapSysNEId;
    WriteMethod write_wapiapSysHostName;
    WriteMethod write_wapiapSysLocation;
    WriteMethod write_wapiBasicManufacturer;
    WriteMethod write_wapiConfigTxPower;
    WriteMethod write_wapiConfigHostName;
    WriteMethod write_wapiConfigHostName;
    WriteMethod write_wapiConfigBeaconInterval;
    WriteMethod write_wapiConfigWirelessModeA;
    WriteMethod write_wapiConfigWirelessModeBG;
	//add by piyp 2008-11-28
	WriteMethod write_wapiConfigWirelessDataRateA;
	WriteMethod	write_wapiConfigWirelessDataRateBG;
	
    WriteMethod write_wapiConfigLanMask;
    WriteMethod write_wapiConfigLanGateway;
    WriteMethod write_wapiConfigLanIP;
    WriteMethod write_wapiConfigDtimPeriod;
    WriteMethod write_wapiConfigReboot;
    WriteMethod write_wapiConfigRtsThreshold;

    //add by piyp 2008-12-26
    WriteMethod write_wapiConfigAutoPower;
	WriteMethod write_wapiConfigAutoAdjustInterval;
    WriteMethod write_wapiNtpServerIP;
    WriteMethod write_wapiSTAAddress;

    /* #0045-2 guoxd_001 20081103 add start */
    /* rekey write funcitons */
    WriteMethod write_wapiConfigUnicastRekeyMethod;
    WriteMethod write_wapiConfigUnicastRekeyTime;
    WriteMethod write_wapiConfigUnicastRekeyPackets;
    /* #0045-2 guoxd_001 20081103 add end */
	
    /* #0045-2 guoxd_002 20081109 add start */
    /* rekey write funcitons */
    WriteMethod write_wapiConfigMulticastRekeyMethod;
    WriteMethod write_wapiConfigMulticastRekeyTime;
    WriteMethod write_wapiConfigMulticastRekeyPackets;

    WriteMethod write_wapiConfigMulticastRekeyStrict;
	//add by piyp 2009-01-13
	WriteMethod write_wapiApAccessMaxUsers;
    /* #0045-2 guoxd_002 20081109 add end */
	WriteMethod write_wapiConfigBKLifetime;
	WriteMethod write_wapiConfigBKReauthThreshold;
	//add by piyp 2008-11-25
	WriteMethod write_wapiConfigLoadBalancePolicy;
	WriteMethod write_wapiConfigLoadBalanceGroupName;
	WriteMethod write_wapiConfigUsersloadValue;
	WriteMethod write_wapiConfigFluxloadValue;
	WriteMethod write_wapiMultiModeAccessStatus;

	WriteMethod write_wapiConfigPSKPassPhrase;  /* #0045-2 guoxd_004 20081129 add+ */
	
	/* #0045-2 guoxd_005 20081225 add start */
	WriteMethod write_wapiConfigMulticastUpdateCount;
	WriteMethod write_wapiConfigCertificateUpdateCount;
	WriteMethod write_wapiConfigUnicastUpdateCount;
	/* #0045-2 guoxd_005 20081225 add end */


    WriteMethod write_sysAcOnlineUserMax;
    WriteMethod write_sysAcPortalCertConnectMax;
    WriteMethod write_sysAcPortalCertConnectCurrent;
    WriteMethod write_sysAcPPPOEConnectMax;
    WriteMethod write_sysAcPPPOEConnectCurrent;
	WriteMethod  write_wapiConfigSATimeout;
	
#define SIOC_SNMPDAGENT_SCAN_AP (SIOCDEVPRIVATE+14) //0x89F0  to 0x89FF	/*ljy--modified to match driver ioctl num*/
#define DEAMON_PATH     "/etc/WAPI/snmp/appara.conf"
#define ALARM_TET_FREQUENCY   60 
/* resend trap alarm , when alarm flag >= 10 */
#define OUT_RESEND_TRAP    10
#define OUT_DELATE_TRAP    100 
struct wirelessSpecStat{  //wireless specific statistics 
	char interface[20];	 //interface name
	int status;	 //Its current state. This is a device dependent information
	int link;	//general quality of the reception
	int level;	//signal strength at the receiver
	int noise;	//silence level (no packet) at the receiver
	int nwid;	//number of discarded packets due to invalid network id
	int crypt;	//number of packet unable to decrypt
	int frag;	//Rx invalid frag
	int retry;	//Tx excessive retries
	int misc;	//Invalid misc
	int beacon;	//Missed beacon
	struct wirelessSpecStat *next; 
};

struct wapiapUserAsso{
	int    ifindex ;
	u_long assoCount ;
	u_long failCount ;
	u_long reassoCount ;
        char   ifname[10];
        u_long userCount;
	struct wapiapUserAsso *next;
};

struct times {
	int year ;
	int month ;
	int day ;
	int hout ;
	int minute ;
	int second ; 
} ;
/*
*----------------------------modify by piyp 200812-20  start----------------------------------------
*/

static char *alarmTypeName[]={"", "Communication Alarm","Environment Alarm","Equipment Alarm","Treatment error Alarm","QoS Alarm"};
struct alarmType{
        int     alarmTypeId;
        char    alarmTypeName[128] ;        
};
typedef struct alarmType  ALAType;

static char *alarmLevelName[]={"", "Serious Alarm","Major Alarm ","Secondary Alarm","Warning Alarm"," Undetermined Alarm"};
struct alarmLevel{
        int     alarmlevelId;
        char    alarmlevelName[128] ;        
};
typedef struct alarmLevel  ALALevel;

struct alarmTable{
        int     alarmID;
        char    alarmName[32] ;
        struct alarmLevel alaLevel ;
        struct alarmType  alaType ;
		int     alarmReasonId;
		char    alarmReason[128];
        time_t  alarmCreatTimes;
        int     alarmState ;
        char    alarmHeading[32] ;
        char    alarmContent[128];
};
typedef struct alarmTable  AAT;

/*
*-------------------modify by piyp 200812-20  end-------------------------------------------
*/

/* 
struct alarmTable{
        int     alarmID;
        char    alarmName[32] ;
        char    alarmLevel[20] ;
        char    alarmType[20] ;
		int     alarmReason;
        time_t  alarmCreatTimes;
        time_t  alarmEliminateTimes ;
        int     alarmState ;
        char    alarmHeading[32] ;
        char    alarmContent[128] ;
};
typedef struct alarmTable  AAT;
*/

struct wapiApAlarmAdmin{
	int times ;
	int flag ;
	struct alarmTable alarmDate;
	struct wapiApAlarmAdmin * next ;
} ;
typedef struct wapiApAlarmAdmin IAAA;

struct wapiApAlarmHead{
        int alarmTimes ;
		time_t oldSysTimes;
        int alarmFlag ;
        struct wapiApAlarmAdmin * next ;
} ;
typedef struct wapiApAlarmHead IAPAH ;

//static char * alarmTypeName[]={"通讯告警","环境告警","设备告警","处理错误告警","服务质量告警"};
//static char * alarmLeveName[]={"严重告警","主要告警","次要告警","警告告警","不确定告警"};
/***********************************************************************************************/
struct snmp_ap_wireless{
	/*lijiyong changed all long type variables to int type in this structure.--2009-03-05*/
	unsigned int signal_strength;		/*AP的信号总强度*/
	unsigned int signaling_pack;		/*AP的信令包数*/
	unsigned int signal_high_strength;		/*AP的最高信号强度*/
	unsigned int signal_low_strength;		/*AP的最低信号强度*/
};

struct agent_snmp_ap_wireless{
unsigned short packetType ;
unsigned short dateLen;
struct snmp_ap_wireless SAW;
};

struct snmp_ap_wireless_1{
	 unsigned long sta_no;		/*使用该信道的终端数*/
   unsigned char sta_stats[10*128]; /*前四个字节表示端口状态，后面6个表示mac地址*/
};
struct agent_snmp_ap_wireless_1 {
unsigned short packetType ;
unsigned short dateLen;
struct snmp_ap_wireless_1 SAW1;
};
typedef struct sta_auth_port_status{
	unsigned char	sta_mac;//关联终端地址
	unsigned int	ctrl_port_status;//受控端口状态
}SAPS;

struct _wapi_stats_Entry{
	unsigned int		wai_sign_errors; /*接收到的WAI分组验证签名错数*/
	unsigned int		wai_hamc_errors; /*接收到的WAI分组消息鉴别码校验出错数*/
	unsigned int		wai_auth_res_fail; /*WAI鉴别结果不成功数*/
	unsigned int		wai_discard; /*接收到的WAI分组被丢弃数*/
	unsigned int		wai_timeout; /*检测到WAI分组超时次数*/
	unsigned int		wai_format_erros; /*检测到WAI分组格式出错数*/
	unsigned int		wai_cert_handshake_fail; /*WAI证书鉴别过程失败次数*/
	unsigned int		wai_unicast_handshake_fail; /*WAI单播密钥协商过程失败次数*/
	unsigned int		wai_multi_handshake_fail; /*WAI组播密钥通告过程失败次数*/
};
typedef struct _wapi_stats_Entry WAPI_STATS_ENTRY;

typedef struct _head_info HEAD_INFO;

/**************************************************/
#define WLAN_BEGIN       "[WLAN_BEGIN]"
#define WLAN_END           "[WLAN_END]"

#define WLAN_CONFIG      "/usr/sbin/wlan.conf"     //modify by sunyushuang0418


//add by piyp 2008-11-24
#define WLAN_11ITEMP_CONFIG      "/etc/wapi/config/wlan11itmp.conf"
#define WLAN_SCRIPT       "/usr/local/boa/htmls/script/wlan_scr"
#define WLAN_SYSINFO    "/etc/wapi/config/ap_sysinfo.conf"
#define AP_UPGRADE_SCR    "/tmp/upgrade_scr"


/* #0045-2 guoxd_001 20081103 add start */
#define WAPI_REKEY_TYPE_UNICAST    0x0001
#define WAPI_REKEY_TYPE_MULTI        0x0002


#define WAPI_REKEY_U_POLICY     0
#define WAPI_REKEY_U_TIME        1
#define WAPI_REKEY_U_PACKET    2

#define WAPI_REKEY_U_POLICY_STR	"REKEY_POLICY"
#define WAPI_REKEY_U_TIME_STR		"REKEY_TIME"
#define WAPI_REKEY_U_PACKET_STR	"REKEY_PACKET"

#define WAPI_REKEY_U_POLICY_NONE     0x0001
#define WAPI_REKEY_U_POLICY_TIME      0x0002
#define WAPI_REKEY_U_POLICY_PACKET  0x0003
#define WAPI_REKEY_U_POLICY_TANDP   0x0004
/* #0045-2 guoxd_001 20081103 add end */

/* #0045-2 guoxd_002 20081109 add start */
#define WAPI_REKEY_M_POLICY     0
#define WAPI_REKEY_M_TIME        1
#define WAPI_REKEY_M_PACKET    2

#define WAPI_REKEY_M_POLICY_STR	"REKEY_M_POLICY"
#define WAPI_REKEY_M_TIME_STR		"REKEY_M_TIME"
#define WAPI_REKEY_M_PACKET_STR	"REKEY_M_PACKET"

#define WAPI_REKEY_M_POLICY_NONE     0x0001
#define WAPI_REKEY_M_POLICY_TIME      0x0002
#define WAPI_REKEY_M_POLICY_PACKET  0x0003
#define WAPI_REKEY_M_POLICY_TANDP   0x0004
/* #0045-2 guoxd_002 20081109 add end */


/* #0045-2 guoxd_005 20081225 add start */
#define WAPI_REPLAY_MIN_VALUE		2
#define WAPI_REPLAY_MAX_VALUE		5

#define WAPI_REPLAY_LIMIT_CERT_STR	"REPLAY_LIMIT_CERT"
#define WAPI_REPLAY_LIMIT_USK_STR	"REPLAY_LIMIT_USK"
#define WAPI_REPLAY_LIMIT_MSK_STR	"REPLAY_LIMIT_MSK"
/* #0045-2 guoxd_005 20081225 add end */

//// add by piyp 2008-12-1

#define END_SCAN_AP 0x0000
#define BLACK_SCAN_AP   0x0001
#define WHITE_SCAN_AP   0x0002

struct start_scan_ap 
{
	unsigned short symbol;
	unsigned short data_len;
	unsigned char data[256];
};


struct vap_traffic_user 
{
	unsigned short tc_contrl;
	unsigned short tc_policy;
	unsigned short tc_other;
};

/* traffic control policy */


#define	IEEE80211_TC_POLICY_DELAY  0x0001
#define	IEEE80211_TC_POLICY_DISCARD  0x0002


#define ADD_FORK 0
#define EDIT_FORK 1
#define DEL_FORK 2
#define FUNC_FORK 3
#define BIT(x) (1<<(x))
#define RECVTIMEOUT			2
#define 	WAI_WEB_PORT			9002
#define 	VERSIONNOW			0x0001	//当前版本号
#define 	AP_RELOAD				0x0212
//#define	AP_RELOAD_RESPONSE	0x0213

/* #0045-2 guoxd_004 20081129 add start */
#define CGI_CMD_RELOAD		0x0212
#define CGI_RELOAD_RESPONSE	0x0213
/* #0045-2 guoxd_004 20081129 add end */

#define	CHECK_CERT				0x0214
#define	CHECK_CERT_RESPNOSE	0x0215
#define CGI_CMD_ADD_DEV	0x0217
#define CGI_CMD_DEL_DEV	0x0218

/* #0045-2 guoxd_001 20081103 add start */
#define CGI_CMD_REKEY      		0x02A1
#define CGI_REKEY_RESPONSE    0x02A2
/* #0045-2 guoxd_001 20081103 add end */

/* #0045-2 guoxd_002 20081109 add start */
#define CGI_CMD_REKEY_M_LEAVE   		0x02A5
#define CGI_REKEY_M_LEAVE_RESPONSE     0x02A6
/* #0045-2 guoxd_002 20081109 add end */

/* #0045-2 guoxd_004 20081126 add start */
#define CGI_CMD_ASUE_LAST_BKID     	    0x02A7
#define CGI_ASUE_LAST_BKID_RESPONSE     0x02A8

#define WAPI_BKID_LEN  					    16
/* #0045-2 guoxd_004 20081126 add end */


/* #0045-2 guoxd_004 20081201 add start */
#define CGI_CMD_BK_LIFE_TIME     	    0x02A9
#define CGI_BK_LIFE_TIME_RESPONSE     0x02AA

#define CGI_CMD_BK_LIFE_PERCENT     	   0x02AB
#define CGI_BK_LIFE_PERCENT_RESPONSE     0x02AC
/* #0045-2 guoxd_004 20081201 add end */


/* #0045-2 guoxd_005 20081225 add start */
#define CGI_CMD_REPLAY_LIMIT_CERT     	    		0x02AD
#define CGI_REPLAY_LIMIT_CERT_RESPONSE      	0x02AE

#define CGI_CMD_REPLAY_LIMIT_USK     	    		0x02AF
#define CGI_REPLAY_LIMIT_USK_RESPONSE      		0x02B0

#define CGI_CMD_REPLAY_LIMIT_MSK     	    		0x02B1
#define CGI_REPLAY_LIMIT_MSK_RESPONSE      		0x02B2
/* #0045-2 guoxd_005 20081225 add end */

//add by piyp 2008-12-31
#define SNMPD_CGI_PORT  9100

#define SNMPD_UPGRADE_PORT  9004

#define MIN_ALARM_UPD                 (0)

#define UPGRADE_ERR_GETFILE    (1)
#define UPGRADE_ERR_FILE          (2)
#define UPGRADE_START               (3)
#define UPGRADE_ERR_FAIL               (4)
#define UPGRADE_SUCCESS            (5)
#define UPGRADE_FINISHED_REBOOT      (6)
#define	ALARM_ID_KEEP_ALIVE_TRAP (7)/*心跳告警*/
 
#define	ALARM_ID_WARM_START	(98)

#define	ALARM_ID_CHANNEL_CHANGED	(9) /*信道改变*/
#define	ALARM_ID_IP_CHANGED	(10) /*IP地址改变*/

#define	ALARM_ID_REMOT_UPGRADE	(26)/*远程升级 */
#define	ALARM_ID_WLAN_RF_A	(27) /* BG卡射频故障  */
#define	ALARM_ID_WLAN_RF_B	(28) /*  A卡射频故障  */
#define	ALARM_ID_WIFI0_USER_NUM	(29)
#define	ALARM_ID_WIFI1_USER_NUM	(30) 

#define ALARM_ID_FUT                    (31)      /* 非法证书用户侵入网络 */
#define ALARM_ID_PA                     (32)     /* 客户端重放攻击 */
#define ALARM_ID_JA                     (33)    /* 篡改攻击 */
#define ALARM_ID_NTP                    (34)   /* 时间同步失败 */
#define ALARM_ID_CHANNEL_DISTURB  (35)  /* 当前信道出现干扰*/ /* #0045-2 guoxd_003 20081117 add+ */
#define ALARM_ID_SECURITY_GRADE_DEBASE_ATTACK  (36)  /* 安全等级降低攻击网管告警*/ /* #0045-2 piyp 20081124 add+ */
#define ALARM_ID_MAC_CHANGED_DIRECTIONAL_ATTACK  (37)  /* 地址重定向攻击网管告警*/ /* #0045-2 piyp 20081124 add+ */
#define ALARM_ID_SUPPLY_CHANNEL_TOO_LOWER  (38) /* 可供使用的信道数过低网管告警*/ /* #0045-2 piyp 20081124 add+ */
#define ALARM_ID_AP_NOT_ADD_NEW_STA  (39)/* AP无法增加新的移动用户*/ /* #0045-2 piyp 20081124 add+ */
#define ALARM_ID_RADIUS_SERVER_NOT_CONNECT_AUTH  (40)/* Radius认证服务器不可达／不可用／无法连接*/ /* #0045-2 piyp 20081124 add+ */
#define ALARM_ID_RADIUS_SERVER_NOT_CONNECT_ACCOUNT  (41)/* 无法连接Radius计费服务器*/ /* #0045-2 piyp 20081124 add+ */
#define	ALARM_ID_FLASH_WRITEERROR	(42) /*FLASH 写错误*/
#define ALARM_ID_FIND_UNSAFE_AP  (43) /*发现不安全AP*/
#define ALARM_ID_CHANNEL_DISTURB_DEVICE  (44) /*出现干扰当前信道的设备网管告警*/
#define ALARM_ID_CHANNEL_DISTURB_STA  (45) /*出现干扰当前信道的客户端网管告警*/
#define ALARM_ID_CHANNEL_DISTURB_AP  (46) /*出现干扰当前信道的AP网管告警*/


#define MAX_ALARM_UDP                (100)    /* #0045-2 guoxd_003 20081117 modify */

#define UPGRADE_SELECT_FLAG   1

#define MIN_ALARM_TIMES  30
#define MAX_ALARM_TIMES  (24*60*60)



struct  wlan_info_t
{
        char dev_name[64];
        char ssid[64];
        char ssid_hide[64];
        char auth[64];
        char psk_type[64];
        char psk_key[128];
        char qos[64];
        char vlan_id[64];
        char mac_cmd[64];
	 char max_user[64];
	 struct  wlan_info_t  *next;
};

struct  wlan_info_t  mbssid_ver;
#define MSSID_NUMBER 15
#define IFNAME_MAX  1000
#define MSSID_ADD       1
#define MSSID_EDIT     2
#define MSSID_DEL        3

struct  mssid_wlan_table
{
	int  flag;
	char wlan[10];
};
int add_valn_is_same_vlanid(char *file_name,   const char *be_key,  const char *end_key,int vlanid) ;
int add_valn_is_same_ssid(char *file_name,   const char *be_key,  const char *end_key,char *wlanInfo) ;
int    add_valn_to_mssid(char *file_name,   const char *be_key,  const char *end_key,int vlanid,struct wlan_info_t  wlanInfo) ;
void    * write_share_memory(const unsigned char *shm_param, const size_t size, AAT * aat);
void    *read_share_memory(const unsigned char *shm_param,  const size_t size, AAT * aat);
void     init_daemon(void) ;
int    init_wlanname_table( char devName[]);
int    find_mssid_wlan(char *file_name, const char *be_key, const char *end_key, char *dev_name);
int    find_mssid_count(char *file_name, const char *be_key, const char *end_key, char *dev_name,int  *findFlag) ;
int    save_MSSID_conf(char *file_name, const char *be_key, const char *end_key, char *value);
int    save_MSSID_conf1(char *file_name, char *be_key,char *end_key, struct wlan_info_t  wlan_scr_info);
int    del_MSSID_conf(char *file_name, char *be_key,char *end_key, unsigned int  modfiyCount);
int    read_upgrade_info();
int    display_message(char message[],int dislen) ;
void display_mssid(struct wlan_info_t mssid);
int    analyze_AP_mess(char message[]);
int    open_socket_upgrade(int *sockid,int portid);
int    free_wlan_list(struct wlan_info_t  **wlan_list);
int    inform_wapid(int cmd,char *send_buf, int len);
int    start_wlan_scr(int operation, struct  wlan_info_t *wlan_scr_info);
int    set_wlan_table(char *file_name, char *be_key,char *end_key, unsigned int  modfiyCount, struct wlan_info_t  wlan_scr_info) ;
int    get_wlan_table(char *file_name, char *be_key,char *end_key, struct wlan_info_t  **wlan_list);
void    free_wlan_table(struct wlan_info_t  **wlan_list);
int    read_essid_name(char ifname[],char essidName[]);
int    iw_get_wifis();
int    iw_enum_wlan_interface( char ifnameList[] );
int    wlan_getioctl_dev_addr(char *dev_mac,char *ifname);
struct wapiapUserAsso * get_ap_assoc(int *num);
int    send_trap_notification();
void    register_callback();
int    find_timeout_alarm(IAPAH * iaa) ;
void set_alarm1( AAT * aat,int id , char *name, int levelId, int typeId, int reasonId, char *reason, time_t ctime, int   state, char *head,  char *content);
void set_alarm( AAT *aat,int id,char *message);
int    collent_wapi_alarm_trap(IAPAH * wapiApAlarm) ;
int    serch_by_name(char *file_name,const char *be_key, const char *end_key, const char *dev_name,struct wlan_info_t *wlan_info);
int    send_trap_string_notification(AAT * aat) ;
int    send_trap_table_notification(AAT * aat);
int    free_ap_assoc(struct wapiapUserAsso * head);	
int    count_mssib(char *file_name,   const char *be_key,  const char *end_key);
int    index_read_SSID(char *file_name, char *be_key,char *end_key, unsigned int  index,struct wlan_info_t *wlan_info_item);
int    save_community_conf(char type, char* filename, char *command, char *key, char *value) ;
int  iw_enum_channel(int ifs, int * channel);
int exec_cmd(const unsigned char *cmd) ;
void  report_RF_trap();
int  get_mac_form_apmess(char message[],char macstr[]);
int  read_port_state(char *file_name,const char *be_key, const char *end_key);

//add by piyp 2008-11-21
int get_trapId(char *filename,char *trapIp, char*trapkey );
int set_trapId(char *filename,char *id,char *trapkey);
int get_ap_access_max_users(int *count);
char * str_replace(const char * s, const char * f, const char * r);

#endif /* WAPIPWLANAP_H */
