//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 9:14:34 AM on Wednesday, February 25, 2004
//
//	Generated for file: C:\gsoap.2.5.2\interop\cw\Rsc\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"interoptA"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainRunAButton                            1001	//(Left Origin = 9, Top Origin = 145, Width = 40, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainRunBButton                            1004	//(Left Origin = 65, Top Origin = 145, Width = 40, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainRunCButton                            1005	//(Left Origin = 113, Top Origin = 145, Width = 40, Height = 14, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUnnamed1003Label                      1003	//(Left Origin = 8, Top Origin = 16, Usable = 1, Font = Standard)
#define MainUnnamed1006Label                      1006	//(Left Origin = 8, Top Origin = 112, Usable = 1, Font = Standard)
#define MainResultsList                           1002	//(Left Origin = 8, Top Origin = 33, Width = 150, Usable = 1, Font = Standard, Visible Items = 7)
#define MainURLList                               1008	//(Left Origin = 9, Top Origin = 73, Width = 142, Usable = 0, Font = Standard, Visible Items = 6)
#define MainURLPopTrigger                         1007	//(Left Origin = 8, Top Origin = 128, Width = 152, Height = 16, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1008)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 46, Top Origin = 22, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

