#!/bin/sh

start()
{
echo "Mounting file systems"
mount -a
mount -o remount +w /
mount -t ramfs -n none /tmp
mount -rw -t jffs2 /dev/mtdblock3 /etc/config
mount -rw -t jffs2 /dev/mtdblock3 /jffs
#mount -t tmpfs tmpfs /dev

mknod /dev/wrcpu c 10 131 >dev/null 2>&1

mkdir -p /jffs/hostapd/
#cp -f /etc/defaults/config.xml /etc/config 

#by liuyanbo
  ln -sf /tmp/resolv.conf.auto /etc/resolv.conf
#add by changzhimin for ppp module
if [ -e /etc/ppp ];then
	ln -sf /etc/resolv.conf	/etc/ppp/resolv.conf
	mkdir -p /var/lock
fi
	if [ ! -f /etc/config/config.xml ]; then
		cp -f /etc/defaults/config.xml /etc/config
	fi
		
	if [ ! -f /etc/config/version ]; then
		xml_upsystem_version="`cat /etc/version/version`"
		echo $xml_upsystem_version > /etc/config/version
	fi
        if [ -e /etc/config/config.xml ];then
	        /usr/sbin/xmlupgrade
        fi
	cp -f /etc/defaults/session.xml /tmp
	if [ -f /jffs/system ];then
		echo "AP"
	else
		cp -f /etc/wlan/system /etc/config
	fi

	if [ -x /jffs/preconfig ];then
		/jffs/preconfig
	else
		cp -f /etc/wlan/preconfig /jffs
		/jffs/preconfig
	fi
	if [ -x /jffs/config.ap83 ];then
		/jffs/config.ap83
	else
		cp -f /etc/wlan/config.ap83 /jffs
		chmod 755 /jffs/config.ap83	
		/jffs/config.ap83
	fi
	if [ -x /jffs/postconfig ];then
		/jffs/postconfig
	else
		cp -f /etc/wlan/postconfig /jffs
		/jffs/postconfig
	fi
	#/usr/sbin/iwevent & 
	#/sbin/rate-stat &
}

stop()
{
    true
}

case "$2" in
  boot)
        start
        ;;
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo "Usage: $0 {boot|start|stop}"
        exit 1
esac

