#!/bin/sh

IWCONFIG=/usr/sbin/iwconfig
IWLIST=/usr/sbin/iwlist

. /usr/lib/web/xmlconf.sh

#usage()
usage()
{
	echo " usage: settxpower2 {ifname} {offset}"
	exit 1
}

#
#get_wifiname( vapname )
#
get_wifiname()
{
	vapname="$1"
#get wifi count
	CONFIG_XML=/tmp/device_info.xml
	local wifi_info=`config_read /device/wifi_total 2>/dev/null`
	local wifi_count=`config_getoption "${wifi_info}" count 2>/dev/null`
	if [ ${wifi_count} -eq 1 ];then
		wifiname="wifi0"
		return 0
	fi
#get wifi name
	CONFIG_XML=/jffs/config.xml
	local thinap=`cat /proc/sys/dev/wifi0/thinap`
        if [  0${thinap} -eq 0 ];then
        	local wifinum=`echo ${vapname} | grep -o '[0-9]\{1,\}'`
        	wifinum=$((wifinum+1))
        	local vap_path="/config/network/vap${wifinum}"
        	local vap_str=`config_read ${vap_path}`
        	wifiname=`config_getoption "$vap_str" wifi`
        else
                local wifinum=`echo ${vapname} | cut -d. -f2 | cut -d- -f1`
                wifiname="wifi${wifinum}"
        fi
	return 0
}

#
#get_wifipower( wifiname )
#
get_wifipower()
{
	CONFIG_XML=/tmp/device_info.xml
	local dev_info_path="/device/wifi_total/wifi_sol/${wifiname}"
	local wifi_info=`config_read "${dev_info_path}" 2>/dev/null`
	powerlimit=`config_getoption "${wifi_info}" max_power`
	return 0	
}

if [ ! $# -eq 2 ];then
	usage
fi

if [ ! -z $1 ];then
	ifname="$1"
fi

if [ ! -z $2 ];then
	offset="$2"
fi

if [ ${offset} -gt 0 ];then
	exit 1
fi

wifiname=""
get_wifiname "${ifname}"

powerlimit=0
get_wifipower "${wifiname}"


if [ -f /jffs/tx-offset -a "${wifiname}" = "wifi0" ];then
	txoffset=`cat /jffs/tx-offset`
	maxpower=$((powerlimit-txoffset))
else
	lineno=`${IWLIST} ${ifname} txpower | wc -l`
	maxpower=`${IWLIST} ${ifname} txpower | awk '{if(NR==lineno){print $1}}' lineno=$((lineno-2))`
fi
static_power=`pro_ctl_util  -i | awk -F[:-] '/product type/{print $2}'`
if [ "$static_power" == "AP2400" ];then
        maxpower=$powerlimit
fi
#static_power=`pro_ctl_util  -i | awk -F: '/product type/{print $2}' | awk -F, '{print $2}'  | grep -o "[0-9]\{1,\}"`
#if [ $static_power -eq 100 ];then
#	maxpower=20
#else
#	maxpower=27
#fi

curpower=$((${maxpower}+${offset}))
if [ ! $? -eq 0 ];then
	echo "parameter error: wrong offset"
	exit 1
fi
if [ ${curpower} -lt 0 ];then
	echo "parameter error: wrong offset"
	exit 1
fi

${IWCONFIG} ${ifname} txpower ${curpower}

 
