#!/bin/sh
#
# source library
#
#
# logo
#
mkdir /tmp/logo
if [ -f /jffs/.OEM/.company_name ] && [ -f /jffs/.OEM/.logo/.logo.jpg ];then
	cp /jffs/.OEM/.logo/.logo.jpg /tmp/logo/logo.jpg
else
	productType=`/usr/sbin/showsysinfo 2>/dev/null|awk -F':' '/Device Type/{print $2}' 2>/dev/null|cut     -b 1-4 2>/dev/null`
	if [ "$productType" == "AP26" ];then
		cp /www/image/xj-AP2600.jpg /tmp/logo/logo.jpg
	elif [ "$productType" == "AP24" ];then
		cp /www/image/xj-AP2400.jpg /tmp/logo/logo.jpg
	elif [ "$productType" == "FH-A" ];then
		cp /www/image/xh.jpg /tmp/logo/logo.jpg
	elif [ "$productType" == "AQ20" ];then
		cp /www/image/autelan.jpg /tmp/logo/logo.jpg
	elif [ "$productType" == "R200" ];then
		cp /www/image/datang.jpg /tmp/logo/logo.jpg
	else
		cp /www/image/autelan.jpg /tmp/logo/logo.jpg
	fi
fi

. /usr/lib/web/constant.sh
. /usr/lib/web/xmlconf.sh
. /usr/lib/web/sysinit.sh
. /usr/lib/web/function.sh
. /etc/wlan/vendor_setup.sh
chown -R root:root /www
chown -R root:root /usr/lib/web
if [ ! -e /etc/config/config.xml ]; then
    cp -f /etc/defaults/config.xml /etc/config/config.xml
fi
if [ -d /jffs/hostapd ];then
	echo "hostapd config dir ok"
else
	mkdir /jffs/hostapd
fi
#
# load the entire configuration
#
local xml_config=`config_read /config`

#
# hostname
#
echo "$HOST_NAME" > /proc/sys/kernel/hostname
if [ -f /jffs/.OEM/.company_name ];then
	echo "`cat /jffs/.OEM/.company_name`" > /proc/sys/kernel/hostname
fi

#prepare config.wtp for wtpd
if [ ! -f /jffs/config.wtp ];then
	cp /etc/wlan/config.wtp /jffs/config.wtp 
fi
cp /jffs/config.wtp /tmp/config.wtp

#
#vendor setup
#

#if [ ! -f /jffs/start_count ];then
#	vendor_cf_setup
#fi

start_count=`cat /jffs/start_count 2>/dev/null || echo 0`
echo $((${start_count}+1)) > /jffs/start_count

if [ -d /jffs/.OEM/.default ];then
	if [ -f /jffs/.OEM/.default/.def_user  ];then
		if [ -f /jffs/.OEM/.default/.def_pass  ];then
			vendor_user=`cat /jffs/.OEM/.default/.def_user`
			vendor_pass=`cat /jffs/.OEM/.default/.def_pass`
			vendor_user_setup "${vendor_user}" "${vendor_pass}"
			sys_user_setup
		fi
	fi
	if [ -f /jffs/.OEM/.default/.def_ssid ];then
		vendor_ssid=`cat /jffs/.OEM/.default/.def_ssid`
		vendor_ssid_setup "${vendor_ssid}"
	fi
	if [ -f /jffs/.OEM/.default/.def_wmode ];then
		vendor_wmode=`cat /jffs/.OEM/.default/.def_wmode`
		vendor_wmode_setup ${vendor_wmode}
	fi
	if [ -d /jffs/.OEM/.default_set ];then
		rm -rf /jffs/.OEM/.default_set
	fi
	mv /jffs/.OEM/.default /jffs/.OEM/.default_set
fi


#/usr/sbin/reg_set

#
# LAN & WLAN
#
echo "cp passwd to /tmp/"
/bin/cp /etc/wlan/etc/passwd /tmp/
sys_user_setup
#route_forward_conf
sys_lan_setup
sys_dns_setup
xml_config=`config_read /config/system`
xml_system_mode=`config_getoption "$xml_config" workmode`
if [ $xml_system_mode == 1 ]; then
	sysctl -w dev.wifi0.thinap=0
	sys_ntp_setup
	sys_vlan_startsetup
	sys_wlan_setup
	sys_security_startsetup
	sys_macfilter_startsetup
	sys_advanceset_startsetup
	sys_wds_setup
	sys_stp_setup
	wired_if_conf
	wireless_if_conf
	#dhcpserver_conf start before netfilter_conf for the dhcpsnooping
	snmp_conf
	dhcpserver_conf
	#adminsec_conf
	#netfilter_conf
	#intelligence_conf
	sys_url_filter
	#rm /sbin/wtpd -rf
	#led set
	#wtpd_enable
	wrcpuutil -d
	wrcpuutil -l -n 0 -s 1
	/sbin/rate-stat &
	sys_lan_setup
	sys_dns_setup
	route_forward_conf
	echo 50 > /proc/sys/net/eth0/maxnumber
else
	sysctl -w dev.wifi0.thinap=1
	if [ ! -f /jffs/process_text ];then
		cp -f /etc/wlan/process_text /jffs
	fi
	if [ -f /jffs/wtp.log.txt ];then
	    echo "wtp.log.txt ok"
	else
		cp -f /etc/wlan/wtp.log.txt /jffs
	fi
	sys_lan_setup
	sys_dns_setup
	route_forward_conf
	thin_wlwan_startsetup
	sys_acktimeout_setup
	if [ -f /jffs/config.wtp ];then
		wtpd > /dev/null 2>&1 &
	else
		cp -f /etc/wlan/config.wtp /jffs
		wtpd > /dev/null 2>&1 &
	fi
#	/etc/wlan/clear_www > /dev/null 2>&1
	/usr/sbin/wtpd_check &
#	/usr/sbin/linkcheck eth0 &
#	/usr/sbin/cpu_util_check &
	if [ -x /jffs/shell  ]; then
		/jffs/shell
	fi
fi
/etc/init.d/mini_httpd start

/usr/sbin/ap_monitor &

#start arping
/etc/wlan/arpnotice > /dev/null 2>&1 &
/etc/wlan/factoryreset > /dev/null 2>&1 &

