#!/bin/sh
wrcpuutil -f
while :
do
sleep 5
factory_reset_flag="`wrcpuutil -L | awk -F " " '/factory reset/ {print $4}'`"
echo $factory_reset_flag
if [ $factory_reset_flag == 3 ]; then
	/sbin/sysfactoryreset
	echo f > /proc/kes_debug_flag
	/sbin/sysreboot
fi
done
