#!/bin/sh /etc/rc.common

KILLALL=/usr/bin/killall

start()
{
	echo 1 > /proc/sys/net/br_igmp/igmp_snooping_switch
	/usr/sbin/igmpsnoop &
}

stop()
{
	echo 0 > /proc/sys/net/br_igmp/igmp_snooping_switch
	$KILLALL igmpsnoop
}
