BINFILE = ndis_disconnect
CFLAGS += -Wall -I$(LC_GENERL_INCLUDE_DIR)
LDFLAGS += -L$(LC_LIB_DIR) -lndis_dail
SRCS += ndis_disconnect.c 

OBJS = $(SRCS:%.c=%.o)
all: $(BINFILE)

prep:

$(BINFILE):$(OBJS)
	$(CC) $(CFLAGS) -o $@  $^ $(LDFLAGS)
	rm -f *.o

clean:
	rm -f *.o $(BINFILE)

install:
	cp -f $(BINFILE) $(INSTALL_ROOT)/usr/sbin/
