#!/bin/sh
/usr/sbin/stop_monitor
if [ $# -ne 1 ] ;then
	echo "Usage: sysupgrade [SYSTEM-FILENAME]"
	exit 1
fi
if [ -e $1 ]; then
	echo "file exist!"
fi
killall wtpd linkcheck arpnotice factoryreset udhcpc telnetd > /dev/null 2>&1
cd /tmp
tar zxvf $1 > /dev/null 2>&1
[ ! -e WNAP550_fwflash ] && [ ! -e WNAP550_magicblk ]
if [ $? -ne 1 ]; then
	logger -s "Invalid firmware file"
	rm -f $1
	exit 2
fi

echo "*** Erasing / Copying magic block image to flash(/dev/mtdblock2)"
dd if=/tmp/WNAP550_magicblk of=/dev/mtdblock2
if [ $? -ne 0 ];
then
	logger -s "ERROR: failed to magic block image"
	rm -f $FIRMWARE_FILE
	exit 3
fi

cp /sbin/reboot /tmp
cp /bin/sleep /tmp
cp /bin/dd /tmp
chmod 755 /tmp
/bin/umount /dev/pts
/bin/umount /proc
/bin/umount -l /
#/bin/umount -a /
echo "*** Erasing / Copying kernel\rootfs image to flash(/dev/mtdblock10)"
/tmp/dd if=/tmp/WNAP550_fwflash of=/dev/mtdblock10
if [ $? -ne 0 ];
then
	logger -s "ERROR: failed to copy kernel image"
	rm -f $FIRMWARE_FILE
	exit 4
fi
/tmp/sleep 1
echo t > /proc/kes_debug_flag
/tmp/reboot -f
