#!/bin/sh

MAX_VAP_NUM=16
MIN_POWER=10
MAX_POWER=20
CONFIG_XML="/jffs/config.xml"
. /usr/lib/web/xmlconf.sh
XPATH_VAP=/config/network/vap
IWCONFIG=/usr/sbin/iwconfig
IWLIST=/usr/sbin/iwlist
TXPOWER=txpower

if [ ! $# -eq 2 ];then
	echo "error:need wifi name and strategy"
	exit 0
fi

#get_vap_name(wifi_name)
#wifi_name : wifi[n] n=0,1,2...
get_vap_name()
{
	local wifi_name="notset"
	local if_name=""
	local vap_str=""
	local num=0
	while [ ! "$wifi_name" = $1 ] && [ $num -lt $MAX_VAP_NUM ] 
	do
		num=$(($num+1))
		vap_str=`config_read ${XPATH_VAP}${num} 2>/dev/null`
		wifi_name=`config_getoption "$vap_str" wifi 2>/dev/null`
	done
	if [ "$wifi_name" = $1 ];then
		echo `config_getoption "$vap_str" if 2>/dev/null`
	fi
}

vap_name_in_wifi=`get_vap_name $1`
if [ ! -n "$vap_name_in_wifi" ];then
	exit 1
fi

outside_frequencies=`$IWLIST ${vap_name_in_wifi} scanning 2>/dev/null | awk -F ":|[ ]+" '/Frequency/{print $3}'`
if [ ! -n "$outside_frequencies" ];then
	exit 1
fi
inside_frequency=`$IWCONFIG $vap_name_in_wifi 2>/dev/null | awk '/Frequency/{print $2}'| awk -F ":|=" '{print $2}'`
echo $outside_frequencies | grep -q $inside_frequency 2>/dev/null
if [ ! $? -eq 0 ];then
	exit 0 
fi

#send_trap DeviceInterferenceDeteted

inside_power=`$IWCONFIG $vap_name_in_wifi | awk '/Tx-Power/{print $4}' | awk -F ":|=" '{print $2}'`

if [ $2 = "inc" ];then
	if [ $inside_power -lt $MAX_POWER ];then
		inside_power=$(($inside_power+1))
	fi
else
	if [ $inside_power -gt $MIN_POWER ];then
		inside_power=$(($inside_power-1))
	fi
fi

$IWCONFIG $vap_name_in_wifi $TXPOWER $inside_power 2>/dev/null


