#!/bin/sh
if [ $# -ne 2 ] ;then
	echo "Usage: set_boot default 1\2"
	exit 1
fi
usage()
{
        echo "set_boot default 1\2"
        exit 1
}
if [ ! $# -eq 2 ];then
        usage
fi
WRCPUUTIL=/usr/bin/pro_ctl_util
case $1 in
  default)
	if [ $2 -eq 2 ];then
		$WRCPUUTIL -V 2 -S 40176
	fi
	if [ $2 -eq 1 ];then
		$WRCPUUTIL -V 1 -S 40176
	fi	
	;;
  *)
	usage
	;;
esac
	
		
