/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef NSCRTVROOT_H
#define NSCRTVROOT_H
#define COUNT_LEN 256
static long VALUE;
static long long_ret;


/* function declarations */
void init_nscrtvRoot(void);
static char *hextob ( char *s );
FindVarMethod var_nscrtvRoot;
FindVarMethod var_eocCBATCardRFTable;
FindVarMethod var_eocCBATCardMACCNUIsolationTable;
FindVarMethod var_eocSoftwareUpgradeTable;
FindVarMethod var_eocCNUWhiteListTable;
FindVarMethod var_eocRealTimeStatisticTable;
    WriteMethod write_eocCBATAdminLogicalID;
    WriteMethod write_eocCBATAdminIPMode;
    WriteMethod write_eocCBATAdminIPAddress;
    WriteMethod write_eocCBATAdminIPMask;
    WriteMethod write_eocCBATAdminIPGateway;
    WriteMethod write_eocCBATAdminDateAndTime;
    WriteMethod write_eocCBATAdminReset;
    WriteMethod write_eocSoftwaretUpgradeServerIP;
    WriteMethod write_eocSoftwareUpgradeServerPort;
    WriteMethod write_eocSoftwareUpgradeLogin;
    WriteMethod write_eocSoftwareUpgradePassWord;
    WriteMethod write_eocCNUWhiteListAmountLimitation;
    WriteMethod write_eocTrapMaxTimes;
    WriteMethod write_eocTrapMinInterval;
    WriteMethod write_eocTrapMaxInterval;
    WriteMethod write_eocCBATCardRFOutputLevel;
    WriteMethod write_eocCBATCardMACCNUIsolationEN;
    WriteMethod write_eocSoftwareUpgradeMACAddress;
    WriteMethod write_eocSoftwareUpgradeDevType;
    WriteMethod write_eocSoftwareUpgradeFileName;
    WriteMethod write_eocSoftwareUpgradeProceed;
    WriteMethod write_eocCNUWhiteListMACAddress;
    WriteMethod write_eocCNUWhiteListAuthorization;

#endif /* NSCRTVROOT_H */
