#!/bin/sh
#this script is used for the production led test ,which is opposite of uplink
#pro_ctl_util -d 13
HW_version="`pro_ctl_util -i | awk -F':' '/HD version/{print $2}'`"
case "$HW_version" in
5.0)
	pro_ctl_util -d 16
	;;
6.0)
	pro_ctl_util -d 22
	;;
*)
	pro_ctl_util -d 22
	;;
esac
