#!/bin/sh

if [ ! $# -eq 7 ];then
echo "usage:createif [devname] [vapname] [mode] [channel] [essid] [qos<0|1>] [chainmask<1|2|3>]"
echo "e.g.  ./.createif wifi0 ath0 11g 1 wireless 0 1"
exit
fi

stop_monitor
killall wtpd

echo 0 > /proc/sys/dev/$1/thinap
wlanconfig $2 destroy
wlanconfig $2 create wlanmode ap wlandev $1
brctl addif default $2

if [ $3 == "11nght40plus" ] && [ $4 != "11" ] && [ $7 != "3" ]; then
    #11ng 40Mhz单流150M（1和6信道）
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11nght40minus" ] && [ $4 == "11" ] && [ $7 != "3" ]; then
    #11ng 40Mhz单流150M（11信道）
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
		ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11nght40minus" ] && [ $4 == "11" ] && [ $7 == "3" ]; then
    #11ng 40Mhz双流300M（11信道）
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
		ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11nght40plus" ] && [ $4 != "11" ] && [ $7 == "3" ]; then
    #11ng 40Mhz双流300M（1和6信道）
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
		ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11nght20" ] && [ $7 != "3" ]; then
    #11ng 20Mhz单流150M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11nght20" ] && [ $7 == "3" ]; then
    #11ng 20Mhz双流300M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11naht40plus" ] && [ $7 != "3" ]; then
    #11na 40Mhz单流150M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11naht20" ] && [ $7 != "3" ]; then
    #11na 20Mhz单流150M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11naht40plus" ] && [ $7 == "3" ]; then
    #11na 40Mhz双流300M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11naht20" ] && [ $7 == "3" ]; then
    #11na 20Mhz双流300M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
#   brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    iwpriv $2 cwmmode 2
    iwpriv $1 txchainmask $7
    iwpriv $1 rxchainmask $7
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11a" ]; then
    #11a 54M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
    brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11g" ]; then
    #11g 54M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    iwconfig $2 channel 0
    iwpriv $2 mode $3
    brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $3 == "11b" ]; then
    #11b 11M
#   echo 0 > /proc/sys/dev/$1/thinap
#   wlanconfig $2 destroy
#   wlanconfig $2 create wlanmode ap wlandev $1
    ifconfig $2 down
    iwconfig $2 channel 0
    iwpriv $2 mode $3
    brctl addif default $2
    iwconfig $2 channel $4
    iwconfig $2 essid $5
    ifconfig $2 up
    ifconfig $2 down
    ifconfig $2 up
fi

if [ $6 == "1" ]; then
    iwpriv $2 switch 16
    iwpriv $2 cwmax 3 0 1
    iwpriv $2 cwmax 3 1 1
    iwpriv $2 cwmin 3 0 1
    iwpriv $2 cwmin 3 1 1
    iwpriv $2 cwmax 1 0 1
    iwpriv $2 cwmax 1 1 1
    iwpriv $2 cwmin 1 1 1
    iwpriv $2 cwmin 1 0 1
    iwpriv $2 cwmin 2 0 1
    iwpriv $2 cwmin 2 1 1
    iwpriv $2 cwmax 2 1 1
    iwpriv $2 cwmax 2 0 1
    iwpriv $2 cwmax 0 0 1
    iwpriv $2 cwmax 0 1 1
    iwpriv $2 cwmin 0 1 1
    iwpriv $2 cwmin 0 0 1
    iwpriv $2 aifs 0 1 0
    iwpriv $2 aifs 0 0 0
    iwpriv $2 aifs 1 0 0
    iwpriv $2 aifs 1 1 0
    iwpriv $2 aifs 2 0 0
    iwpriv $2 aifs 2 1 0
    iwpriv $2 aifs 3 0 0 
    iwpriv $2 aifs 3 1 0
fi
