#!/bin/sh
tc qdisc del dev eth0 root 2> /dev/null > /dev/null
tc qdisc add dev eth0 root handle 1: htb default 10
tc class add dev eth0 parent 1: classid 1:1 htb rate 1mbit burst 5K
tc class add dev eth0 parent 1:1 classid 1:10 htb rate 1mbit burst 5k
tc qdisc add dev eth0 parent 1:10 handle 10: prio bands 4 priomap 2 3 3 3 1 3 0 0 1 1 1 1 1 1 1 1
