#!/bin/sh
#
#board management
#

cd /lib/modules/2.6.15/net/
#insmod pro_ctl_mod.ko;
insmod ag7240_mod.ko
#create device information file
DEVICE_MODEL="`/usr/bin/pro_ctl_util -i | awk -F ":" '/product type/{print $2}'`"
echo "$DEVICE_MODEL"
device_info $DEVICE_MODEL
PCI_POLICY=""
if [ -f /jffs/ccode ];then
		C_CODE=`cat /jffs/ccode`
		PCI_POLICY="countrycode=${C_CODE}"
else
		PCI_POLICY="countrycode=156"	
fi
if [ -f /jffs/.mac-policy ];then	
	PCI_POLICY="${PCI_POLICY} new_dispatch_mac=2"
else
	PCI_POLICY="${PCI_POLICY} new_dispatch_mac=1"
fi

if [ -f /jffs/art_flag ]; then
	cd /lib/modules/2.6.15/net/
	insmod art.ko
	mdk_client.out &	
else
	cd /lib/modules/2.6.15/net/
	insmod ath_hal.ko;
	insmod wlan.ko;
	#insmod ath_dfs.ko;
	insmod ath_rate_atheros.ko;
	insmod ath_dev.ko ${PCI_POLICY} 
	#insmod ath_ahb.ko;
	insmod ath_pci.ko;
	insmod ath_pktlog.ko;
	insmod wlan_acl.ko;
	insmod wlan_ccmp.ko;
	insmod wlan_scan_ap.ko;
	insmod wlan_scan_sta.ko;
	insmod wlan_tkip.ko;
	insmod wlan_wep.ko;
	insmod wlan_xauth.ko;
	insmod capwap_split_fast.ko;
fi
	



# loopback
#
ifconfig lo 127.0.0.1
ifconfig eth0 up
ifconfig eth1 up 

#Reboot Count
REBOOT_COUNT=0
if [ -f /jffs/reboot_count ];then
	REBOOT_COUNT=`cat /jffs/reboot_count`	
fi

REBOOT_COUNT=$((${REBOOT_COUNT}+1))
echo ${REBOOT_COUNT} > /jffs/reboot_count
cp /etc/wlan/etc/passwd /tmp/
echo Autelan > /proc/sys/kernel/hostname
sleep 2
stop_monitor
killall wtpd
