#!/bin/sh
#showsysinfo
#echo "==========================="
#echo "system check:"
#/usr/sbin/mount_check
#/usr/sbin/dev_check
#echo "==========================="
#cp /jffs/* /etc/config -rf
#cp /etc/config/* /jffs -rf
#killall wtpd
#echo 0 >/proc/sys/dev/wifi0/thinap

# insmod etho
cd /lib/modules/2.6.31/net/
insmod athrs_gmac.ko

# loopback
#i
ifconfig lo 127.0.0.1

#set mac
mac_base="`/usr/sbin/showsysinfo | awk -F ":" '/MAC/{print $2$3$4$5$6$7}'`"
#set eth mac
	ifconfig eth0 down
	ifconfig eth1 down
		mac_org_formed=`set_mac org ${mac_base} `
    ifconfig eth0 hw ether $mac_org_formed
		mac_org_formed=`set_mac upper ${mac_base} `
    ifconfig eth1 hw ether $mac_org_formed
    ifconfig eth0 up
    ifconfig eth1 up

brctl addbr default
brctl setfd default 1
brctl addif default eth0
brctl addif default eth1
ifconfig default 0.0.0.0 up

#ln -sf /etc/wlan/etc/passwd /tmp/passwd
#
#REBOOT_COUNT=0
#if [ -f /jffs/reboot_count ];then
#  REBOOT_COUNT=`cat /jffs/reboot_count`
#fi
# REBOOT_COUNT=$((${REBOOT_COUNT}+1)) 
# echo ${REBOOT_COUNT} > /jffs/reboot_count
