/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: apAttributeInfo.h
* description:  implementation for the header file of apAttributeInfo.c
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef APATTRIBUTEINFO_H
#define APATTRIBUTEINFO_H

/* function declarations */
void init_apAttributeInfo(void);
FindVarMethod var_apAttributeInfo;
    WriteMethod write_apSysName;
    WriteMethod write_apDivideSSIDCount;
    WriteMethod write_apBussinessSSIDPriority;
    WriteMethod write_apNetAdminSSIDPriority;
    WriteMethod write_apChannelPattern;
    WriteMethod write_apWiFi0HopFreqDetectInterval;
    WriteMethod write_apWiFi1HopFreqDetectInterval;
    WriteMethod write_apPlatToTerminalCertAccount;
    WriteMethod write_apPlatToTerminalCertPassword;

#endif /* APATTRIBUTEINFO_H */
