/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: apCounterInfo.h
* description:  implementation for the header file of apCounterInfo.c
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef APCOUNTERINFO_H
#define APCOUNTERINFO_H

#define  COUNT_LEN    256
#define  COUNT_MAX   512

 void CGetChar(int *sum, char* Src);

double GetPercentage(int firstNumber, int secondNumber);

/* function declarations */
void init_apCounterInfo(void);
FindVarMethod var_apCounterInfo;

#endif /* APCOUNTERINFO_H */
