/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: apGeneralInfo.h
* description:  implementation for the header file of apGenernalInfo.c
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef APGENERALINFO_H
#define APGENERALINFO_H

/* function declarations */
void init_apGeneralInfo(void);
FindVarMethod var_apGeneralInfo;
    WriteMethod write_SysTime;
    WriteMethod write_PrimDNSServerIPAdd;
    WriteMethod write_SeconDNSServerIPAdd;
    WriteMethod write_ReadCommunityName;
    WriteMethod write_WriteCommunityName;
    WriteMethod write_StatWindowTime;
    WriteMethod write_SampleTime;
    WriteMethod write_HeartbeatPeriod;
    WriteMethod write_SysRemoteRestart;
    WriteMethod write_SysRestart;
    WriteMethod write_SysReset;
    WriteMethod write_CPUusageThreshhd;
    WriteMethod write_MemUsageThreshhd;
    WriteMethod write_RogueApTrigger;
	WriteMethod write_setPingIPaddr;
	WriteMethod write_setPingIPv6addr;
#endif /* APGENERALINFO_H */
