/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: apGlobalInfo.h
* description:  implementation for the header file of apGlobalInfo.c
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef APGLOBALINFO_H
#define APGLOBALINFO_H

/* function declarations */
void init_apGlobalInfo(void);
FindVarMethod var_apGlobalInfo;
    WriteMethod write_apCreateVapValue;
    WriteMethod write_apDestroyVapValue;

#endif /* APGLOBALINFO_H */
