/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: apGlobalInfo.c
* description:  implementation for the creation and destroy of vap
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "apGlobalInfo.h"

/* 
 * apGlobalInfo_variables_oid:
 *   this is the top level oid that we want to register under.  This
 *   is essentially a prefix, with the suffix appearing in the
 *   variable below.
 */

//oid apGlobalInfo_variables_oid[] = { 1,3,6,1,4,1,31656,2,3,2,1,5 };
oid *apGlobalInfo_variables_oid;
/* 
 * variable4 apGlobalInfo_variables:
 *   this variable defines function callbacks and type return information 
 *   for the apGlobalInfo mib section 
 */

struct variable4  apGlobalInfo_variables[] = {
/*  magic number        , variable type , ro/rw , callback fn  , L, oidsuffix */
#define APCREATEVAPVALUE		1
{APCREATEVAPVALUE,  ASN_OCTET_STR,  RWRITE,  var_apGlobalInfo, 1,  { 1 }},
#define APDESTROYVAPVALUE		2
{APDESTROYVAPVALUE,  ASN_OCTET_STR,  RWRITE,  var_apGlobalInfo, 1,  { 2 }},

};
/*    (L = length of the oidsuffix) */


/** Initializes the apGlobalInfo module */
void
init_apGlobalInfo(void)
{
  //  'cat  /jffs/.OEM/.vendor_oid'
    FILE *fp;
    char oid_str[64]={0};
  	char oid_tmp[64]={0};
  	int  oid_len=0;
  	int  count = 0;
  	char *p = NULL;
  	char *ptr=NULL;
	
    fp=fopen( "/jffs/.OEM/.vendor_oid","r");
    if(fp)
    {
		memset(oid_str,0,64);
    	fgets(oid_str,sizeof(oid_str),fp);
		oid_str[strlen(oid_str)-1] = '\0';
		fclose(fp);
    }
    else
    {
		memset(oid_str,0,64);
     	strcpy(oid_str, "1.3.6.1.4.1.31656"); 
	}

	memset(oid_tmp,0,64);
	strcpy(oid_tmp,oid_str);
		 
    ptr = strtok(oid_tmp, "."); 
	while(NULL != ptr)
	{
		oid_len++;
		ptr = strtok(NULL,".");
	 }
	
    oid_len = oid_len + 5;	
	apGlobalInfo_variables_oid=(oid *)malloc(sizeof(oid)*(oid_len));
	

	p = strtok(oid_str, ".");
    while( NULL != p)
    {
       apGlobalInfo_variables_oid[count++] = (oid)atoi(p);
       p = strtok(NULL,".");
    }
    apGlobalInfo_variables_oid[count ++] = 2;
    apGlobalInfo_variables_oid[count ++] = 3;
    apGlobalInfo_variables_oid[count ++] = 2;
    apGlobalInfo_variables_oid[count ++] = 1;
    apGlobalInfo_variables_oid[count ++] = 5;

    DEBUGMSGTL(("apGlobalInfo", "Initializing\n"));

    /* register ourselves with the agent to handle our mib tree */
    REGISTER_MIB_NEW("apGlobalInfo", apGlobalInfo_variables, variable4,
               apGlobalInfo_variables_oid,count);

    /* place any other initialization junk you need here */
}

/*
 * var_apGlobalInfo():
 *   This function is called every time the agent gets a request for
 *   a scalar variable that might be found within your mib section
 *   registered above.  It is up to you to do the right thing and
 *   return the correct value.
 *     You should also correct the value of "var_len" if necessary.
 *
 *   Please see the documentation for more information about writing
 *   module extensions, and check out the examples in the examples
 *   and mibII directories.
 */
unsigned char *
var_apGlobalInfo(struct variable *vp, 
                oid     *name, 
                size_t  *length, 
                int     exact, 
                size_t  *var_len, 
                WriteMethod **write_method)
{
    /* variables we may use later */
    static long long_ret;
    static u_long ulong_ret;
    static unsigned char string[128];
    static oid objid[MAX_OID_LEN];
    static struct counter64 c64;

    if (header_generic(vp,name,length,exact,var_len,write_method)
                                  == MATCH_FAILED )
    return NULL;

    /* 
   * this is where we do the value assignments for the mib results.
   */
    switch(vp->magic) {
    case APCREATEVAPVALUE:
	  memset(string,0,128);
        *write_method = write_apCreateVapValue;
         strcpy(string,"create a new vap");
	   *var_len = strlen (string);
         return (u_char*) string;
  
	case APDESTROYVAPVALUE:
	  memset(string,0,128);
        *write_method = write_apDestroyVapValue;
         strcpy(string,"destroy a vap");
	   *var_len = strlen (string);
          return (u_char*) string;
    default:
      ERROR_MSG("");
    }
    return NULL;
}





int
write_apCreateVapValue(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    static char value[128];
    static char string[128];
    static char buffer[128];
    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to apGlobalInfo not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len >32* sizeof(char)) {
              fprintf(stderr,"write to apGlobalInfo: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:
         

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
                memset (value,0,128 );
                memset (string,0,128 );
                memset (buffer,0,128 );
		  memcpy(value,var_val,var_val_len);
		  value[var_val_len]='\0';
                wireless_create_vap( "wifi0", value );
		  sprintf(string,"%s  %s  %s","/usr/sbin/iwconfig",value,"essid   ChinaNet");
	         system(string);
		  sprintf(buffer,"%s  %s   %s","/sbin/ifconfig",value,"up");	 
		  system(buffer);
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}


int
write_apDestroyVapValue(int      action,
            u_char   *var_val,
            u_char   var_val_type,
            size_t   var_val_len,
            u_char   *statP,
            oid      *name,
            size_t   name_len)
{
    static char value[128];

    switch ( action ) {
        case RESERVE1:
          if (var_val_type != ASN_OCTET_STR) {
              fprintf(stderr, "write to apGlobalInfo not ASN_OCTET_STR\n");
              return SNMP_ERR_WRONGTYPE;
          }
          if (var_val_len > 32*sizeof(char)) {
              fprintf(stderr,"write to apGlobalInfo: bad length\n");
              return SNMP_ERR_WRONGLENGTH;
          }
          break;

        case RESERVE2:

          break;

        case FREE:
             /* Release any resources that have been allocated */
          break;

        case ACTION:
          		memset (value,0,128);
			memcpy(value,var_val,var_val_len);
		       value[var_val_len]='\0';
                      wireless_destroy_vap(value);
          break;

        case UNDO:
             /* Back out any changes made in the ACTION case */
          break;

        case COMMIT:
             /*
              * Things are working well, so it's now safe to make the change
              * permanently.  Make sure that anything done here can't fail!
              */
          break;
    }
    return SNMP_ERR_NOERROR;
}

