/**********************************************************************************
* Copyright (c) 2008-2011  Beijing Autelan Technology Co. Ltd.
* All rights reserved.
*
* filename: apPropertyTable.h
* description:  implementation for the header file of apPropertyTable.c
* 
*
* 
************************************************************************************/

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef APPROPERTYTABLE_H
#define APPROPERTYTABLE_H

static struct PT_Tbl_data {


char  apDomainName  [ 128 ];
long  apAssociUsrCount;
int  apUsrTotalTime;
char  apNoiseLevel  [ 128 ];
long  apQoswmmFunction;
char  apWirelessQosConfig [ 128 ];
char  apWEPVap1asciiKey1  [ 128 ];
char  apWEPVap1asciiKey2  [ 128 ];
char  apWEPVap1asciiKey3  [ 128 ];
char  apWEPVap1asciiKey4  [ 128 ];

char  apWEPVap2asciiKey1  [ 128 ];
char  apWEPVap2asciiKey2  [ 128 ];
char  apWEPVap2asciiKey3  [ 128 ];
char  apWEPVap2asciiKey4  [ 128 ];

char  apWEPVap1hexKey1 [ 128 ];
char  apWEPVap1hexKey2  [ 128 ];
char  apWEPVap1hexKey3  [ 128 ];
char  apWEPVap1hexKey4  [ 128 ];

char  apWEPVap2hexKey1  [ 128 ];
char  apWEPVap2hexKey2  [ 128 ];
char  apWEPVap2hexKey3  [ 128 ];
char  apWEPVap2hexKey4  [ 128 ];
}nPk,*pk = &nPk;


/* function declarations */
void init_apPropertyTable(void);
FindVarMethod var_apPropertyTable;
    WriteMethod write_apQoswmmFunction;
    WriteMethod write_apWirelessQosConfig;
    WriteMethod write_apWEPVap1asciiKey1;
    WriteMethod write_apWEPVap1asciiKey2;
    WriteMethod write_apWEPVap1asciiKey3;
    WriteMethod write_apWEPVap1asciiKey4;
    WriteMethod write_apWEPVap2asciiKey1;
    WriteMethod write_apWEPVap2asciiKey2;
    WriteMethod write_apWEPVap2asciiKey3;
    WriteMethod write_apWEPVap2asciiKey4;
    WriteMethod write_apWEPVap1hexKey1;
    WriteMethod write_apWEPVap1hexKey2;
    WriteMethod write_apWEPVap1hexKey3;
    WriteMethod write_apWEPVap1hexKey4;
    WriteMethod write_apWEPVap2hexKey1;
    WriteMethod write_apWEPVap2hexKey2;
    WriteMethod write_apWEPVap2hexKey3;
    WriteMethod write_apWEPVap2hexKey4;


#endif /* APPROPERTYTABLE_H */
