#!/bin/sh

#
#usage()
#
usage()
{
	echo "link_bad_redhcp {disable|enable}"
	exit 1
}

if [ ! $# -eq 1 ];then
	usage
fi

if [ $1 = "disable" ];then
	rm -f /jffs/ndcheck_dhcp_enable
	killall ndcheck_dhcp
elif [ $1 = "enable" ];then 
	killall ndcheck_dhcp
	touch /jffs/ndcheck_dhcp_enable
	/usr/sbin/ndcheck_dhcp > /dev/null 2>&1 &	
else
	usage
fi


