#!/bin/sh
########################################
#system upgrad tool for web GUI,ap83
#parameter numbers check and usage
if [ $# -ne 1 ] ;then
	echo "Usage: sysupgrade [SYSTEM-FILENAME]"
	exit 1
fi
############################################
#if file exist 
if [ -e $1 ]; then
	echo "file exist!"
	size=$(ls -l $1 | awk -F " " '{print $5}')
	echo "$size byte"
	if [ $size -lt 5242880 ] || [ $size -gt 15663104 ];then
	     logger -s "wrong size"
	     exit 1
	fi	
	cat /www/reboot.htm >/dev/null
	cat /sbin/sysreboot >/dev/null
#	cp /usr/sbin/update_img_tool /tmp/
 #   	(free&&date&&/tmp/update_img_tool if=$1 ke=/dev/mtdblock1 fs=/dev/mtdblock2&&free&&date)>/tmp/sysupgradelog 2>&1
	cp /usr/bin/ap83-firmware-upgrade-web /tmp/
	/usr/sbin/stop_monitor & >/dev/null 2>&1
	echo 0 > /proc/sys/dev/wifi0/monitor_process    
	(free&&date&&/tmp/ap83-firmware-upgrade-web $1 &&free&&date)>/tmp/sysupgradelog 2>&1
   	 mv /tmp/sysupgradelog /jffs/sysupgradelog
fi

