#!/bin/sh

prog=mini_httpd

start()
{
    /sbin/mini_httpd -d /www -u root
}

stop()
{
    killall mini_httpd
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo "Usage: $prog {start|stop}"
        exit 1
esac
