#!/bin/sh
#this script is used for the production led test ,which is opposite of up2Gled
#pro_ctl_util -d 17
HW_version="`pro_ctl_util -i | awk -F':' '/HD version/{print $2}'`"
case "$HW_version" in
5.0)
	pro_ctl_util -d 17
	;;
6.0)
	pro_ctl_util -d 17
	;;
*)
pro_ctl_util -d 15
pro_ctl_util -d 19
	;;
esac
