#!/bin/sh
tc qdisc del dev eth0 root 2> /dev/null > /dev/null
tc qdisc add dev eth0 root handle 1: htb default 30

tc class add dev eth0 parent 1: classid 1:1 htb rate 1mbit burst 5K
tc class add dev eth0 parent 1:1 classid 1:10 htb rate 80kbit ceil 1mbit burst 5k prio 0
tc class add dev eth0 parent 1:1 classid 1:20 htb rate 40kbit ceil 1mbit burst 5k prio 1
tc class add dev eth0 parent 1:1 classid 1:30 htb rate 20kbit ceil 1mbit burst 5k prio 2
tc class add dev eth0 parent 1:1 classid 1:40 htb rate 10kbit ceil 1mbit burst 5k prio 3

tc qdisc add dev eth0 parent 1:10 handle 10: sfq perturb 10
tc qdisc add dev eth0 parent 1:20 handle 20: sfq perturb 10
tc qdisc add dev eth0 parent 1:30 handle 30: sfq perturb 10
tc qdisc add dev eth0 parent 1:40 handle 40: sfq perturb 10

tc filter add dev eth0 parent 1:0 protocol ip prio 0 u32 match ip tos 0xe0 0xff flowid 1:10
tc filter add dev eth0 parent 1:0 protocol ip prio 0 u32 match ip tos 0x88 0xff flowid 1:10
tc filter add dev eth0 parent 1:0 protocol ip prio 1 u32 match ip tos 0xa0 0xff flowid 1:20
tc filter add dev eth0 parent 1:0 protocol ip prio 3 u32 match ip tos 0x20 0xff flowid 1:40
