#!/bin/sh

if [ $# -ne 1 ];
then
	echo "$0 <firmware-file> "
	exit 1
fi

# Get firmware image 
echo "*** Begin to firmware upgrade..."
mv $1 /tmp/wg102_firmware.bin   
if [ $? -ne 0 ];
then
	exit 2
fi

nohup /usr/sbin/autelan-firmware-upgrade-file /tmp/wg102_firmware.bin > /tmp/nohup.out
if [ $? -ne 0 ]; then
				touch NOHUP_ERROR
        exit 1
fi
exit 0
