#!/bin/sh /etc/rc.common
IPTABLES=/usr/bin/iptables
AUTELAN=/usr/sbin/autelan
DETECT_DOS=/usr/sbin/detect_dos
KILLALL=/usr/bin/killall
wlan_name=ath0

if [ ! -z $1 ];then
	wlan_name="$1"
fi

start()
{
	$IPTABLES -N SYN_FLOOD 2>/dev/null 
	$IPTABLES -A INPUT -p tcp --syn -j SYN_FLOOD 2>/dev/null
	$IPTABLES -A SYN_FLOOD -m limit --limit 600/sec --limit-burst 600 -j RETURN 2>/dev/null
	$IPTABLES -A SYN_FLOOD -j LOG --log-prefix "SYN_FLOOD_DETECTED:" --log-level 4 2>/dev/null
	$IPTABLES -A SYN_FLOOD -j DROP 2>/dev/null
	$AUTELAN traffic_limit $wlan_name set_vap_flag 1
	$AUTELAN traffic_limit $wlan_name set_vap 512
	$DETECT_DOS ${wlan_name} & 
}

stop()
{
	$KILLALL detect_dos 2>/dev/null
	$AUTELAN traffic_limit $wlan_name set_vap_flag 0 
	$IPTABLES -D INPUT -p tcp --syn -j SYN_FLOOD 2>/dev/null
	$IPTABLES -F SYN_FLOOD 2>/dev/null
	$IPTABLES -X SYN_FLOOD 2>/dev/null
}
