#!/bin/sh

OPT_FILE=/proc/sys/dev

#usage()
#usage
usage()
{
    echo "usage:"
    echo "          setantenna wifi[n] diversity [0/1]"
    echo "                                                      0: on 1:off"
    echo "          setantenna wifi[n] tx [0/1/2]"
    echo "                                              0:auto 1:main 2:aux"
    exit 1
}

#get_div_opt( wifiname, usr_opt )
#high-txp can not set opt_num to 1
get_div_opt()
{
	if  test ${NORMAL} -eq 0 && test  "${1}" = "wifi0" ;then
		echo -n 0
		return 0
	fi
	echo -n ${2}
}

#get_tx_opt( wifiname, usr_opt )
#normal   main:2   aux:1
#high-txp main:1   aux:2
#abg        main:2   aux:1
get_tx_opt()
{
    if test ${ISNOTNG} -eq 0 ;then
		echo -n ${2}
		return 0
    fi
    if test ${ISCAVIUM} -eq 0 ;then
		echo -n ${2}
		return 0
    fi
    if  test ${NORMAL} -eq 0 && test  "${1}" = "wifi0" && test -f /jffs/tx-offset ;then
		echo -n ${2}
		return 0
    fi
    if test -f /tmp/.senao-card ;then 
 	        echo -n ${2}
		return 0
    fi
    case ${2} in
    	0)
    		echo -n 0
    	;;
    	1)
    		echo -n 2
    	;;
    	2)
    		echo -n 1
    	;;
    	*)
    		usage
    	;;
    esac
}

if [ ! $# -eq 3 ];then
    usage
fi

if [ ! -e ${OPT_FILE}/${1}  ];then
    echo "error: ${1} not exist"
    exit 1
fi

cat /tmp/device_info.xml | awk '/product_model/' | grep -q "\-H"
NORMAL=$?
RESET_FLAG=0
#pei add
cat /tmp/device_info.xml | awk '/product_model/' | grep -v "\-H" | grep -q "AQ2010"
ISCAVIUM=$?
cat /tmp/device_info.xml | awk '/product_model/' | grep -E -q "(AQ2010V2-H|WG)"
ISNOTNG=$?

case ${2} in
    diversity)
        OPT_FILE=${OPT_FILE}/${1}/diversity
        OPT_NUM=`get_div_opt ${1} ${3}`
		if [ ${OPT_NUM} -eq 1 ];then
			RESET_FLAG=1
		fi
    ;;
    tx)
	OPT_FILE_TMP=${OPT_FILE}/${1}/rxantenna
        OPT_FILE=${OPT_FILE}/${1}/txantenna
        OPT_NUM=`get_tx_opt ${1} ${3}`
	echo ${OPT_NUM} > ${OPT_FILE_TMP} 
    ;;
    rx)
	OPT_FILE=${OPT_FILE}/${1}/rxantenna
	OPT_NUM=`get_tx_opt ${1} ${3}`
    ;;
    *)
        usage
    ;;
esac    
    
#echo "echo ${OPT_NUM} > ${OPT_FILE}"
echo ${OPT_NUM} > ${OPT_FILE}

#if [ ${RESET_FLAG} -eq 1 ];then
#    /sbin/sysreboot
#fi
