#
# Makefile for advanced NAT
#
obj-$(CONFIG_IP_NF_RTSP) += ip_conntrack_rtsp.o
obj-$(CONFIG_IP_NF_NAT_RTSP) += ip_nat_rtsp.o

obj-$(CONFIG_IP_NF_MATCH_CLASSIFY) += ipt_classify.o
obj-$(CONFIG_IP_NF_MATCH_WEBSTR) += ipt_webstr.o
obj-$(CONFIG_IP_NF_TARGET_IMQ) += ipt_IMQ.o
