#!/bin/sh
showsysinfo
echo "==========================="
echo "system check:"
/usr/sbin/mount_check
/usr/sbin/dev_check
echo "==========================="
#cp /jffs/* /etc/config -rf
#cp /etc/config/* /jffs -rf
#killall wtpd
#echo 0 >/proc/sys/dev/wifi0/thinap
