#!/bin/sh
while :
do
sleep 2

button_reset_flag=`avrutil -L | awk -F":|[ ]+" '/button_factory_reset_get/{print $4}'`
remote_reset_flag=`avrutil -L | awk -F":|[ ]+" '/^factory_reset_get/{print $4}'`

if [ ${button_reset_flag} -gt 40 ] || [ ${remote_reset_flag} -gt 15 ]; then
	/sbin/sysfactoryreset
	echo f > /proc/kes_debug_flag
	/sbin/sysreboot
fi
if [ $remote_reset_flag == 200 ]; then
	poweroff
fi
done
